const char* chart;
chart += "<body>\n";
chart += "\n";
chart += "\t<h1>Pflanze1</h1>\n";
chart += "\n";
chart += "    <form method=\"POST\" action=\"/amount\">\n";
chart += "        <input type=\"radio\" name=\"amount1\" value=\"low\" checked> Low\n";
chart += "        <input type=\"radio\" name=\"amount1\" value=\"medium\"> Medium\n";
chart += "        <input type=\"radio\" name=\"amount1\" value=\"high\"> High\n";
chart += "        <input type=\"submit\" value=\"Submit\">\n";
chart += "    </form>\n";
chart += "\t<h1>Pflanze2</h1>\n";
chart += "\n";
chart += "\t<form method=\"POST\" action=\"/amount\">\n";
chart += "\t\t\t<input type=\"radio\" name=\"amount2\" value=\"low\" checked> Low\n";
chart += "\t\t\t<input type=\"radio\" name=\"amount2\" value=\"medium\"> Medium\n";
chart += "\t\t\t<input type=\"radio\" name=\"amount2\" value=\"high\"> High\n";
chart += "\t\t\t<input type=\"submit\" value=\"Submit\">\n";
chart += "\t</form>\n";
chart += "</body>";
